examples/5-using-a-database/README.md

The README title for the "Using A Database" example was copied but not updated from the "Working With JSON" example.

Update database example README title

---

src/wisp.gleam

Hello 🙂 
I've noticed that the parameter had the wrong name since the function is dealing with JSON and not HTML.
I haven't found any other occurrences for `json_response` that would require an update, just this one file, and the test suite passes.

Fix json_response parameter name

---

examples/0-hello-world/gleam.toml

If it's OK for you, I can create pull requests for other examples as I read them :)

fix: remove warnings about transitive dependencies imports

---

README.md

Hello 👋 
I found a mistake in the middleware snippet.
I suppose that there's no need for a change log entry for such a minor fix? I'll add it if it's needed 🙂

Fixed a mistake in the README

---

src/wisp.gleam

Potentialy a copy-paste error from the html_response function.

Use json_response in json_response example

---

CHANGELOG.md
gleam.toml
manifest.toml
src/wisp.gleam

While building a Wisp application, I was receiving a `deprecated value` notice due to simplifile:
```
warning: Deprecated value used
┌─ /Users/markholmes/Development/pf/app/backend/build/packages/wisp/src/wisp.gleam:1381:22
│
1381 │       case simplifile.is_file(path) {
│                      ^^^^^^^^ This value has been deprecated
It was deprecated with this message: Use `verify_is_file` instead
```
This PR seeks to address this warning by bumping simplifile to v1.4 and replacing usage of `simplifile.is_file` with `simplifile.verify_is_file`.

Update simplifile to 1.4

---

examples/01-routing/README.md
examples/02-working-with-form-data/README.md
examples/03-working-with-json/README.md
examples/04-working-with-other-formats/README.md
examples/05-using-a-database/README.md
examples/06-serving-static-assets/README.md
examples/07-logging/README.md
examples/08-working-with-cookies/README.md
examples/09-configuring-default-responses/README.md

Fix a bunch of broken example links in the README docs

Fix example links in README docs

---

examples/05-using-a-database/README.md
examples/06-serving-static-assets/README.md
examples/07-logging/README.md
examples/08-working-with-cookies/README.md
examples/09-configuring-default-responses/README.md
examples/10-working-with-files/README.md
examples/10-working-with-files/src/app/router.gleam

In examples:
- fix a broken link
- improve consistency of readme headers and link texts
- fix some "this example shows how to..." paragraphs not matching their examples
- fix a few typos in comments in the "working with files" example

Fix typos, inconsistencies, and a broken link in examples

---

src/wisp.gleam

It seems to be necessary and it seems like the docs aren't in sync but I might be wrong.

Add 'request' param to set_cookie examples

---

src/wisp.gleam

The 'get_cookie' example is not in sync with the arguments required for this function.

Add 'Security' param to get_cookie example

---

src/wisp.gleam

There was a typo in string_body docs. 
Related issue: https://github.com/gleam-wisp/wisp/issues/74

(docs): Fix string_body example typo: using string_builder_body.

---

CHANGELOG.md
src/wisp.gleam
src/wisp_ffi.erl

This PR replaces `escape_html`'s implementation with an optimised version to make it faster and more memory efficient

Optimise html_escape

---

CHANGELOG.md
gleam.toml
manifest.toml
src/wisp.gleam

:wave:
This PR updates simplifile to 2.0.0. The update required one code change due to a [renamed function in simplifile](https://github.com/bcpeinhardt/simplifile/blob/main/CHANGELOG.md#v200---1-june-2024).

update simplifile to 2.0.0

---

examples/00-hello-world/src/app.gleam
examples/01-routing/src/app.gleam
examples/02-working-with-form-data/src/app.gleam
examples/03-working-with-json/src/app.gleam
examples/04-working-with-other-formats/src/app.gleam
examples/05-using-a-database/src/app.gleam
examples/06-serving-static-assets/src/app.gleam
examples/07-logging/src/app.gleam
examples/08-working-with-cookies/src/app.gleam
examples/09-configuring-default-responses/src/app.gleam
examples/10-working-with-files/src/app.gleam
src/wisp.gleam
src/wisp/internal.gleam
src/wisp/wisp_mist.gleam

Preceding pr #72 and comment: https://github.com/gleam-wisp/wisp/pull/72#pullrequestreview-2176235813
This is just the split of the existing mist functions and code from the main wisp module.
An internal module has been added to allow code share between wisp and any web server implementation such as mist.
Mist has been entirely removed from the main wisp.gleam and wisp/internal.gleam files.

Mist module split

---

src/wisp.gleam

I think this is what was meant in the docstring.
Thank you for making Wisp and Gleam and the related projects :)

Fix typo in docstring

---

CHANGELOG.md
gleam.toml
manifest.toml
src/wisp/internal.gleam

Fixes #9 
As `directories.tmp_file()` returning `Error(Nil)` means that `/tmp/` or similar didn't exist, a good fallback would be the current working directory

Use the directories package to detect a temp directory

---

gleam.toml
manifest.toml
src/wisp.gleam
src/wisp_ffi.erl
test/wisp_test.gleam

This PR adds `houdini` as a dependency used to escape HTML. Houdini is basically that same piece of code plus some tweaks to make it even faster! Also turns out wisp wasn't escaping `'` characters, so I've updated one of the failing tests

Use houdini to escape html

---

examples/09-configuring-default-responses/src/app/web.gleam

Given that 304 is used for the etag. This default responses middleware should not change the 304 to a 303. Same for other status codes not explicitly handled.

Do not redirect on 304

---

src/wisp.gleam

From
The `content-type` header will be set to `text/html`.
To
The `content-type` header will be set to `text/html; charset=utf-8`.
Because the `wisp.html_response()` sets `text/html; charset=utf-8` as a `content-type header`
```gleam
pub fn html_response(html: StringTree, status: Int) -> Response {
HttpResponse(
status,
[#("content-type", "text/html; charset=utf-8")],
Text(html),
)
}
```

Doc update for wisp.html_response

---

README.md
examples/README.md
examples/src/configuring_default_responses/README.md
examples/src/hello_world/README.md
examples/src/logging/README.md
examples/src/routing/README.md
examples/src/serving_static_assets/README.md
examples/src/using_a_database/README.md
examples/src/working_with_cookies/README.md
examples/src/working_with_files/README.md
examples/src/working_with_form_data/README.md
examples/src/working_with_json/README.md
examples/src/working_with_other_formats/README.md

After collapse of the examples, the documentation no longer reflects the correct commands for running the examples.
Updated documentation to describe how they can be run, and fixed some references that were pointing to a fork.
Added relative links directly to tests.

Update Wisp example documentation after collapse
